### ISSUE TITLE
LLAMA 2 HF tokenizer len is 32001, 迅雷7B model异常需更新。

### ISSUE THREAD

**Issue by seuwins** [LlamaFamily/Llama-Chinese#291]
Fix link：https://github.com/ggerganov/llama.cpp/issues/3900

**Comment by Rayrtfr** [comment]
> Fix link：[ggerganov/llama.cpp#3900](https://github.com/ggerganov/llama.cpp/issues/3900)

试试这个：https://github.com/LlamaFamily/Llama-Chinese/tree/main/inference-speed/CPU/ggml
