### ISSUE TITLE
各位大神，为什么 pip install -r requirements.txt 时，里面依赖的版本有些找不到呢，请指教一下。

### ISSUE THREAD

**Issue by githup-cuikang** [LlamaFamily/Llama-Chinese#304]
torch==2.1.2 # 版本找不到
bitsandbytes==0.42.0
accelerate==0.27.2 # 版本找不到
numpy==1.26.4
gekko==1.0.6
pandas
scipy
sentencepiece==0.2.0
datasets
evaluate
pytest
peft==0.8.2
transformers==4.38.1
scikit-learn
torchvision
torchaudio
tensorboard
gradio
flash_attn==2.5.5

**Comment by moffefei** [comment]
遇到同样的问题，把requirements.txt里面的torch==2.1.2改成torch==2.0.0即可。
accelerate类似处理
