### ISSUE TITLE
开源模型，做了屏蔽词管理么？

### ISSUE THREAD

**Issue by RyanOvO** [LlamaFamily/Llama-Chinese#313]
如题，譬如微调训练时，输入内容含有 自杀、跳楼等敏感词汇，模型是否做了这些敏感词汇的工程管理。

**Comment by LlamaFamily** [comment]
目前会在输入输出做敏感词检测，微调也有数据做对齐限制

**Comment by doforce** [comment]
llama.family既没有备案也不是在国内域名提供商购买的，而是在godaddy买的，部署在aws的香港节点上。这样的自我审查自我阉割，无非是要在国内宣传卖课而已 
![image](https://github.com/LlamaFamily/Llama-Chinese/assets/17078475/6fcdb089-f63a-4d51-b0f5-2d2ba9c78f15)
，


同时下载模型提升添加微信才能下载，完全玩得是国内厂商拉新宣传的那一套

![image](https://github.com/LlamaFamily/Llama-Chinese/assets/17078475/517f87d2-68a5-426e-9805-50b1d21ea33b)

**Comment by LlamaFamily** [comment]
HuggingFace魔搭都有公开模型下载你看不到吗，你先把网站内容用明白了再说话好吧，你要是有好的安全技术欢迎在社区贡献啊，没必要故意黑吧
