### ISSUE TITLE
挂羊头卖狗肉？

### ISSUE THREAD

**Issue by raintoway** [LlamaFamily/Llama-Chinese#316]
<img width="1403" alt="截屏2024-04-22 09 15 20" src="https://github.com/LlamaFamily/Llama-Chinese/assets/38103330/b2584186-6050-4588-b179-c2e71c836348">
<img width="1410" alt="截屏2024-04-22 09 15 15" src="https://github.com/LlamaFamily/Llama-Chinese/assets/38103330/433d3f25-47c7-4174-9254-2eba17ad73b6">

**Comment by Rayrtfr** [comment]
> <img alt="截屏2024-04-22 09 15 20" width="1403" src="https://private-user-images.githubusercontent.com/38103330/324299546-b2584186-6050-4588-b179-c2e71c836348.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzI1MzcsIm5iZiI6MTcxMzc3MjIzNywicGF0aCI6Ii8zODEwMzMzMC8zMjQyOTk1NDYtYjI1ODQxODYtNjA1MC00NTg4LWIxNzktYzJlNzFjODM2MzQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA3NTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZjc3NzhiYjNkYjc0YzI0NTBjNTIyZjY1ZDhmYmM5YmQyODEzMzkzOGU2YTEyNDVhM2I2ZWU3NmVhOTZlNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vSaqsMuOv-sKsYqjO1VJsnHxc8cStV3LDBob5oraPKU"> <img alt="截屏2024-04-22 09 15 15" width="1410" src="https://private-user-images.githubusercontent.com/38103330/324299554-433d3f25-47c7-4174-9254-2eba17ad73b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzI1MzcsIm5iZiI6MTcxMzc3MjIzNywicGF0aCI6Ii8zODEwMzMzMC8zMjQyOTk1NTQtNDMzZDNmMjUtNDdjNy00MTc0LTkyNTQtMmViYTE3YWQ3M2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA3NTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzYzkzMmRmMWUzZmExMGE2ZGM2YTMwY2U4YjNkNjYyYzNiMDY4NTc5MTFkMzA4MzAzZDdkMWVlMTQ5ODAxZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wxg7DzJRdN13yoVzLSxKAmWJegaNWrGivMiI6weHmh4">

确实是社区的llama3模型，可以再试试
