### ISSUE TITLE
官网主页bug

### ISSUE THREAD

**Issue by doforce** [LlamaFamily/Llama-Chinese#328]
点击官网主页的笑脸图标并没有像预想的那样跳到[huggingface](https://huggingface.co)，而是跟隔壁GitHub图标一样跳到仓库地址
![image](https://github.com/LlamaFamily/Llama-Chinese/assets/17078475/57626567-c71a-4821-aa2c-dd4636cf21d2)

**Comment by ZHangZHengEric** [comment]
我去找人，是吗

**Comment by ZHangZHengEric** [comment]
感谢，已经修复
